-- AlterTable
ALTER TABLE "da_post_procurement_inbox" ALTER COLUMN "final_rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "gst" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "unit_price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "da_post_procurement_outbox" ALTER COLUMN "final_rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "gst" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "unit_price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "da_pre_procurement_inbox" ALTER COLUMN "rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_rate" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "da_pre_procurement_outbox" ALTER COLUMN "rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_rate" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "pre_procurement_history" ALTER COLUMN "rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_rate" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "sr_pre_procurement_inbox" ALTER COLUMN "rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_rate" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "sr_pre_procurement_outbox" ALTER COLUMN "rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_rate" SET DATA TYPE DOUBLE PRECISION;
